### ISSUE TITLE
xml.etree.ElementTree.ParseError: Premature end of file.

### ISSUE THREAD

**Issue by cmci** [jiptool/jip#37]
When I try to resolve dependency with the following code:

```python
from jip.embed import require

require("net.imagej:imagej:2.0.0-rc-42")
from net.imagej import ImageJ
ij = ImageJ()
```

It returns error and terminates (see below). If you could fix [here in maven.py](https://github.com/jiptool/jip/blob/master/jip/maven.py#L108-L121), it wil be veryhelpful! 

```
... ...
jip [Checking] pom file /Users/miura/.m2/repository/org/jhotdraw/jhotdraw/7.6.0/jhotdraw-7.6.0.pom
jip [Checking] pom file /Users/miura/.m2/repository/net/imagej/imagej-ui-awt/0.3.0/imagej-ui-awt-0.3.0.pom
Traceback (most recent call last):
  File "testij2.py", line 3, in <module>
    require("net.imagej:imagej:2.0.0-rc-42")
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/site-packages/jip-0.9.9-py2.7.egg/jip/embed.py", line 38, in require
    artifact_set = _resolve_artifacts([artifact])
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/site-packages/jip-0.9.9-py2.7.egg/jip/commands.py", line 129, in _resolve_artifacts
    more_dependencies = pom_obj.get_dependencies()
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/site-packages/jip-0.9.9-py2.7.egg/jip/maven.py", line 197, in get_dependencies
    dep_mgmt = self.get_dependency_management()
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/site-packages/jip-0.9.9-py2.7.egg/jip/maven.py", line 155, in get_dependency_management
    dependency_management_version_dict.update(parent.get_dependency_management())
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/site-packages/jip-0.9.9-py2.7.egg/jip/maven.py", line 153, in get_dependency_management
    parent = self.get_parent_pom()
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/site-packages/jip-0.9.9-py2.7.egg/jip/maven.py", line 121, in get_parent_pom
    eletree = self.get_element_tree()
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/site-packages/jip-0.9.9-py2.7.egg/jip/maven.py", line 114, in get_element_tree
    self.eletree = parser.close()
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/xml/etree/ElementTree.py", line 1656, in close
    self._raiseerror(v)
  File "/usr/local/Cellar/jython/2.7.0/libexec/Lib/xml/etree/ElementTree.py", line 1508, in _raiseerror
    raise err
  File "<string>", line None
xml.etree.ElementTree.ParseError: Premature end of file.
```

**Comment by baztian** [comment]
Currently it says 

    [Error] Artifact not found: net.imagej:imagej:2.0.0-rc-42

Can you please provide an updated example?
